set client_min_messages = WARNING;
alter table if exists audio_content drop constraint if exists FKix9txcmbtfnx03wdoi39j7x85;
alter table if exists audio_content_transcriptions drop constraint if exists FK_AudioContent_Transcriptions;
alter table if exists collection drop constraint if exists FKcrmp66fva3vixtnov93u5440w;
alter table if exists collection drop constraint if exists FKdc064neuyn6sunxfacbi5at4i;
alter table if exists collection_point_of_interest drop constraint if exists FK_Collection_PointOfInterest_2_Collection;
alter table if exists collection_point_of_interest drop constraint if exists FK_Collection_PointOfInterest_2_PointOfInterest;
alter table if exists collection_sub_collections drop constraint if exists FKkjfuvbyqr3lwirpt5ey9lc7s1;
alter table if exists collection_sub_collections drop constraint if exists FK_Collection_SubCollections;
alter table if exists collection_titles drop constraint if exists FK_Collection_Titles;
alter table if exists content_localized_descriptions drop constraint if exists FK_Content_LocalizedDescriptions;
alter table if exists content_base drop constraint if exists FKjqx8vosh0mrtgryjoj08ds1p2;
alter table if exists content_base drop constraint if exists FKef8a3o5txo46dednif7c5p12c;
alter table if exists exhibition_languages drop constraint if exists FK_Exhibition_Languages;
alter table if exists exhibiton drop constraint if exists FK56penodk9he830xmrefkmbpne;
alter table if exists image_content drop constraint if exists FK353uqh50v8rdf9up7dfi84tkw;
alter table if exists point_of_interest drop constraint if exists FK3frsykf6ciam2mqbfudxju5q6;
alter table if exists point_of_interest drop constraint if exists FKhdqnpvseant3hlkj2d1yc98n8;
alter table if exists point_of_interest_descriptions drop constraint if exists FK_PointOfInterest_Descriptions;
alter table if exists point_of_interest_titles drop constraint if exists FK_PointOfInterest_Titles;
alter table if exists slideshow_content drop constraint if exists FKewuvuxkr1qd19h0vmb0xij1cj;
alter table if exists slideshow_content_slides drop constraint if exists FKowduvqnilsoi2r4juo4pm69d6;
alter table if exists slideshow_content_slides drop constraint if exists FK_SlideshowContent_Slides;
alter table if exists text_content drop constraint if exists FK7r53boms9yocxwbccrmg5lmyo;
alter table if exists text_content_long_texts drop constraint if exists FK_TextContent_LongTexts;
alter table if exists text_content_short_texts drop constraint if exists FK_TextContent_ShortTexts;
alter table if exists video_content drop constraint if exists FK9oemcpw6o5531fy2too5m4bug;
alter table if exists video_content_sources drop constraint if exists FK_VideoContent_Sources;
alter table if exists visit_history_point_of_interest drop constraint if exists VisitHistory_PointOfInterest_2_VisitHistory;
alter table if exists visit_history_point_of_interest drop constraint if exists FK_VisitHistory_PointOfInterest_2_PointOfInterest;
alter table if exists visitor_visit_histories drop constraint if exists FKg50q43k3xc84tbuoann6saguj;
alter table if exists visitor_visit_histories drop constraint if exists FK_Visitor_VisitHistories;
drop table if exists audio_content cascade;
drop table if exists audio_content_transcriptions cascade;
drop table if exists collection cascade;
drop table if exists collection_point_of_interest cascade;
drop table if exists collection_sub_collections cascade;
drop table if exists collection_titles cascade;
drop table if exists content_localized_descriptions cascade;
drop table if exists content_base cascade;
drop table if exists creator cascade;
drop table if exists exhibition_languages cascade;
drop table if exists exhibiton cascade;
drop table if exists image_content cascade;
drop table if exists point_of_interest cascade;
drop table if exists point_of_interest_descriptions cascade;
drop table if exists point_of_interest_titles cascade;
drop table if exists slideshow_content cascade;
drop table if exists slideshow_content_slides cascade;
drop table if exists text_content cascade;
drop table if exists text_content_long_texts cascade;
drop table if exists text_content_short_texts cascade;
drop table if exists video_content cascade;
drop table if exists video_content_sources cascade;
drop table if exists visit_history cascade;
drop table if exists visit_history_point_of_interest cascade;
drop table if exists visitor cascade;
drop table if exists visitor_visit_histories cascade;
drop sequence if exists global_seq;
