@startuml

entity Points <RichType> <<(R, ffccdd)>> {
    points: Integer <<ge: 0, le: 100>>
}

entity Duration <RichType> <<(R, ffccdd)>> {
    minutes: Integer <<ge: 0, le: 250>>
}

entity Email <RichType> <<(R, ffccdd)>> {
    address: String <<nn>>
}

@enduml