@startuml
'https://plantuml.com/class-diagram

hide empty methods
hide empty attributes

!include enums.puml
!include richtypes.puml

entity Person <Entity> {
    firstName: String <<nn, length=64>>,
    lastName: String <<nn, length=64>>
}

entity Teacher <Entity> {
    email: Email <<nn>>
}

entity Student <Entity> {
    ' do we want to store attendance here as well?
    ' actually the idea would be to go from course to sessions to attendance
    ' but what about a total of missed sessions?
    ' the same goes for hand-ins
}

entity Course <Entity> {
    name: String <<nn, length=64>>,
    terms: Set<SchoolTerm>
    type: CourseType,
    isCollege: Boolean,
    level: ClassLevel,
    students: Set<Student>,
    sessions: Set<Session>,
    teacher: Teacher <<nn>>
}

entity Term <Entity> {
    startDate: ZonedDateTime
    endDate: ZonedDateTime
}

entity Session <Entity> {
    date: ZonedDateTime
    topic: String <<nn, length=128>>,
    attendance: Set<Attendance>
}

entity Attendance <Entity> <<(V, bbFFcc)>> {
    student: Student <<nn>>,
    notes: String <<length=1024>>,
    grading: SessionGrading <<embedded>>
}

entity Test <Entity> <<(V, bbFFcc)>> {
    date: ZonedDateTime <<nn>>
    duration: Duration <<embedded>>
    type: TestType
    maximumPoints: Points <<embedded>>
    handIns: Set<HandIn>
}

entity Assignment <ValueObject> <<(V, bbFFcc)>> {
    topics: String <<nn, length=256>>
    blob: Blob <<nn>>
}

entity HandIn <Entity> <<(V, bbFFcc)>> {
    student: Student <<nn>>
    grade: Grade <<nullable, embedded>>
    blob: Blob <<nullable>>
}

' relations
Course *-up- Test
Course *-- Session
Test o- HandIn
Course *-up- Student
Student o- Attendance
Session *- Attendance
Student o-up- HandIn
HandIn -up-> Points : receives
Term *- Course : has
Test -left-> Duration
Test -up-> Points : contains
Test -down-> Assignment
Student -down-|> Person : is a
Teacher -down-|> Person : is a
Course <- Teacher : teaches
Teacher -> Email : has

@enduml